// Generated by deno task build from src/projects/retro-pixel/app.ts.
// Do not edit this file directly; edit the TypeScript source instead.
(() => {
  // src/shared/js/dom.ts
  function requireElement(id, constructor) {
    const element = document.getElementById(id);
    if (!(element instanceof constructor)) {
      throw new Error(`Required element #${id} is missing or has an unexpected type.`);
    }
    return element;
  }
  function canvasContext2d(canvas, options) {
    const context = canvas.getContext("2d", options);
    if (!context) {
      throw new Error("2D canvas context is unavailable.");
    }
    return context;
  }
  function errorMessage(error, fallback) {
    return error instanceof Error && error.message ? error.message : fallback;
  }

  // src/projects/retro-pixel/app.ts
  var imageInput = requireElement("imageInput", HTMLInputElement);
  var folderInput = requireElement("folderInput", HTMLInputElement);
  var dropZone = requireElement("dropZone", HTMLElement);
  var dropZonePlaceholder = requireElement("dropZonePlaceholder", HTMLElement);
  var originalPreview = requireElement("originalPreview", HTMLElement);
  var previewImg = requireElement("previewImg", HTMLImageElement);
  var removeBtn = requireElement("removeImage", HTMLButtonElement);
  var pickFilesBtn = requireElement("pickFilesBtn", HTMLButtonElement);
  var pickFolderBtn = requireElement("pickFolderBtn", HTMLButtonElement);
  var clearQueueBtn = requireElement("clearQueueBtn", HTMLButtonElement);
  var fileName = requireElement("fileName", HTMLElement);
  var queueList = requireElement("queueList", HTMLElement);
  var outputCanvas = requireElement("outputCanvas", HTMLCanvasElement);
  var emptyState = requireElement("emptyState", HTMLElement);
  var sizeLabel = requireElement("sizeLabel", HTMLElement);
  var pixelSize = requireElement("pixelSize", HTMLInputElement);
  var pixelValue = requireElement("pixelValue", HTMLElement);
  var paletteSelect = requireElement("paletteSelect", HTMLSelectElement);
  var ditherSelect = requireElement("ditherSelect", HTMLSelectElement);
  var brightness = requireElement("brightness", HTMLInputElement);
  var brightnessValue = requireElement("brightnessValue", HTMLElement);
  var contrast = requireElement("contrast", HTMLInputElement);
  var contrastValue = requireElement("contrastValue", HTMLElement);
  var saturation = requireElement("saturation", HTMLInputElement);
  var saturationValue = requireElement("saturationValue", HTMLElement);
  var noise = requireElement("noise", HTMLInputElement);
  var noiseValue = requireElement("noiseValue", HTMLElement);
  var scanlines = requireElement("scanlines", HTMLInputElement);
  var preserveAlpha = requireElement("preserveAlpha", HTMLInputElement);
  var crtGlow = requireElement("crtGlow", HTMLInputElement);
  var pixelGrid = requireElement("pixelGrid", HTMLInputElement);
  var alphaThreshold = requireElement("alphaThreshold", HTMLInputElement);
  var saveBtn = requireElement("saveBtn", HTMLButtonElement);
  var saveZipBtn = requireElement("saveZipBtn", HTMLButtonElement);
  var ctx = canvasContext2d(outputCanvas);
  var sourceImage = null;
  var currentObjectUrl = null;
  var isGif = false;
  var gifLoopId = null;
  var gifLastFrameTime = 0;
  var gifFrames = null;
  var gifFrameIndex = 0;
  var gifFrameElapsed = 0;
  var gifDecodeToken = 0;
  var currentFile = null;
  var currentFileName = "";
  var renderRequestId = null;
  var batchQueue = [];
  var batchActiveKey = "";
  var batchBusy = false;
  var effectBufferCanvas = document.createElement("canvas");
  var effectBufferCtx = canvasContext2d(effectBufferCanvas);
  var downscaleCanvas = document.createElement("canvas");
  var downscaleCtx = canvasContext2d(downscaleCanvas, {
    willReadFrequently: true
  });
  var ditherBuffer = new Float32Array(0);
  var GIF_TARGET_FPS = 24;
  var GIF_FRAME_INTERVAL = 1e3 / GIF_TARGET_FPS;
  var GIFUCT_JS_URL = "../../shared/vendor/gifuct.js";
  var GIF_JS_URL = "../../shared/vendor/gif.js";
  var GIF_WORKER_URL = "../../shared/vendor/gif.worker.js";
  var previewModal = new PreviewModal();
  var coreFiles = window.AppCore.files;
  var coreZip = window.AppCore.zip;
  var coreIngestUi = window.AppCore.ingestUi;
  var corePreview = window.AppCore.preview;
  var coreGifDecode = window.AppCore.gifDecode;
  var coreGifEncode = window.AppCore.gifEncode;
  var palettes = {
    original: null,
    gameboy: [
      [
        15,
        56,
        15
      ],
      [
        48,
        98,
        48
      ],
      [
        139,
        172,
        15
      ],
      [
        155,
        188,
        15
      ]
    ],
    cga: [
      [
        0,
        0,
        0
      ],
      [
        255,
        0,
        255
      ],
      [
        0,
        255,
        255
      ],
      [
        255,
        255,
        255
      ]
    ],
    pico8: [
      [
        0,
        0,
        0
      ],
      [
        29,
        43,
        83
      ],
      [
        126,
        37,
        83
      ],
      [
        0,
        135,
        81
      ],
      [
        171,
        82,
        54
      ],
      [
        95,
        87,
        79
      ],
      [
        194,
        195,
        199
      ],
      [
        255,
        241,
        232
      ],
      [
        255,
        0,
        77
      ],
      [
        255,
        163,
        0
      ],
      [
        255,
        236,
        39
      ],
      [
        0,
        228,
        54
      ],
      [
        41,
        173,
        255
      ],
      [
        131,
        118,
        156
      ],
      [
        255,
        119,
        168
      ],
      [
        255,
        204,
        170
      ]
    ],
    amber: [
      [
        20,
        10,
        0
      ],
      [
        90,
        40,
        0
      ],
      [
        255,
        160,
        40
      ],
      [
        255,
        220,
        140
      ]
    ],
    matrix: [
      [
        10,
        4,
        0
      ],
      [
        64,
        28,
        0
      ],
      [
        160,
        74,
        12
      ],
      [
        249,
        115,
        22
      ]
    ],
    mono: [
      [
        0,
        0,
        0
      ],
      [
        85,
        85,
        85
      ],
      [
        170,
        170,
        170
      ],
      [
        255,
        255,
        255
      ]
    ]
  };
  function looksLikeGif(file) {
    const type = (file && file.type ? file.type : "").toLowerCase();
    if (type === "image/gif") return true;
    const name = (file && file.name ? file.name : "").toLowerCase();
    return name.endsWith(".gif");
  }
  function loadGifFrames(file, token) {
    return coreGifDecode.loadGifFrames(file, token, {
      gifuctUrl: GIFUCT_JS_URL,
      frameInterval: GIF_FRAME_INTERVAL,
      isTokenValid: (t) => t === gifDecodeToken
    });
  }
  function setSaveButtonState(label, disabled) {
    saveBtn.textContent = label;
    saveBtn.disabled = disabled;
  }
  function updateSaveButtonLabel() {
    if (!sourceImage) {
      setSaveButtonState("\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C PNG", true);
      return;
    }
    setSaveButtonState(isGif ? "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C GIF" : "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C PNG", false);
  }
  function normalizeQueuePath(file, relativePath) {
    return coreFiles.normalizePath(relativePath || file.webkitRelativePath || file.name) || file.name;
  }
  function makeQueueKey(file, relativePath) {
    return `${normalizeQueuePath(file, relativePath)}|${file.size}|${file.lastModified}`;
  }
  function renderQueueList() {
    coreIngestUi.renderQueue({
      queueList,
      items: batchQueue,
      isBusy: batchBusy,
      getItemId: (item) => item.key,
      isActive: (item) => item.key === batchActiveKey,
      getName: (item) => item.file.name || "file",
      getPath: (item) => item.relativePath && item.relativePath !== item.file.name ? item.relativePath : "",
      getBadgeClass: (item) => {
        const hasSavedState = Boolean(item.savedState && !item.savedState.isGif);
        return item.key === batchActiveKey ? "processing" : hasSavedState ? "saved" : "pending";
      },
      getBadgeText: (item) => {
        const hasSavedState = Boolean(item.savedState && !item.savedState.isGif);
        return item.key === batchActiveKey ? "\u0432\u044B\u0431\u0440\u0430\u043D" : hasSavedState ? "\u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E" : "\u043D\u043E\u0432\u044B\u0439";
      }
    });
  }
  function updateQueueSummary() {
    if (!batchQueue.length) {
      fileName.textContent = sourceImage ? currentFileName || "\u0424\u0430\u0439\u043B \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043D" : "\u041E\u0447\u0435\u0440\u0435\u0434\u044C \u043F\u0443\u0441\u0442\u0430";
      return;
    }
    const activeItem = batchQueue.find((item) => item.key === batchActiveKey);
    const activeLabel = activeItem ? ` \u0412\u044B\u0431\u0440\u0430\u043D: ${activeItem.file.name}.` : "";
    fileName.textContent = `\u0424\u0430\u0439\u043B\u043E\u0432 \u0432 \u043E\u0447\u0435\u0440\u0435\u0434\u0438: ${batchQueue.length}.${activeLabel}`;
  }
  function updateBatchButtons() {
    coreIngestUi.updateIngestButtons({
      pickFilesBtn,
      pickFolderBtn,
      clearQueueBtn,
      fileInput: imageInput,
      folderInput,
      zipBtn: saveZipBtn,
      busy: batchBusy,
      queueLength: batchQueue.length
    });
  }
  function setBatchBusy(isBusy) {
    batchBusy = Boolean(isBusy);
    renderQueueList();
    updateBatchButtons();
  }
  function syncActiveQueueWithFile(file) {
    if (!file || !batchQueue.length) return;
    const match = batchQueue.find((item) => item.file === file);
    if (match) {
      batchActiveKey = match.key;
    }
    renderQueueList();
    updateQueueSummary();
  }
  function clearCurrentImageState(options = {}) {
    const skipSummary = options.skipSummary;
    if (currentObjectUrl) {
      URL.revokeObjectURL(currentObjectUrl);
      currentObjectUrl = null;
    }
    resetGifState();
    isGif = false;
    currentFile = null;
    currentFileName = "";
    sourceImage = null;
    updateSaveButtonLabel();
    sizeLabel.textContent = "\u2014";
    emptyState.style.display = "grid";
    ctx.clearRect(0, 0, outputCanvas.width, outputCanvas.height);
    imageInput.value = "";
    folderInput.value = "";
    clearPreview();
    if (previewModal.isOpen) {
      previewModal.close();
    }
    if (!skipSummary) {
      updateQueueSummary();
    }
  }
  function getBatchQueueItems() {
    return batchQueue.slice();
  }
  function findQueueItemByKey(key) {
    return batchQueue.find((item) => item.key === key) || null;
  }
  function capturePixelControls() {
    return {
      pixelSize: String(pixelSize.value),
      palette: String(paletteSelect.value),
      dither: String(ditherSelect.value),
      brightness: String(brightness.value),
      contrast: String(contrast.value),
      saturation: String(saturation.value),
      noise: String(noise.value),
      scanlines: Boolean(scanlines.checked),
      preserveAlpha: Boolean(preserveAlpha.checked),
      crtGlow: Boolean(crtGlow.checked),
      pixelGrid: Boolean(pixelGrid.checked),
      alphaThreshold: Boolean(alphaThreshold.checked)
    };
  }
  function applyPixelControls(snapshot) {
    if (!snapshot) return;
    if (snapshot.pixelSize !== void 0) pixelSize.value = snapshot.pixelSize;
    if (snapshot.palette !== void 0) paletteSelect.value = snapshot.palette;
    if (snapshot.dither !== void 0) ditherSelect.value = snapshot.dither;
    if (snapshot.brightness !== void 0) brightness.value = snapshot.brightness;
    if (snapshot.contrast !== void 0) contrast.value = snapshot.contrast;
    if (snapshot.saturation !== void 0) saturation.value = snapshot.saturation;
    if (snapshot.noise !== void 0) noise.value = snapshot.noise;
    scanlines.checked = Boolean(snapshot.scanlines);
    preserveAlpha.checked = Boolean(snapshot.preserveAlpha);
    crtGlow.checked = Boolean(snapshot.crtGlow);
    pixelGrid.checked = Boolean(snapshot.pixelGrid);
    alphaThreshold.checked = Boolean(snapshot.alphaThreshold);
  }
  function captureCurrentPixelState() {
    if (!sourceImage || !outputCanvas.width || !outputCanvas.height) {
      return null;
    }
    if (isGif) {
      return null;
    }
    return {
      isGif: false,
      controls: capturePixelControls(),
      outputDataUrl: outputCanvas.toDataURL("image/png")
    };
  }
  function saveActiveQueueItemState() {
    const activeItem = findQueueItemByKey(batchActiveKey);
    if (!activeItem) return;
    const snapshot = captureCurrentPixelState();
    if (!snapshot) return;
    activeItem.savedState = snapshot;
  }
  function drawOutputCanvasFromDataUrl(dataUrl) {
    return new Promise((resolve) => {
      if (!dataUrl) {
        resolve(false);
        return;
      }
      const image = new Image();
      image.onload = () => {
        outputCanvas.width = image.naturalWidth || image.width;
        outputCanvas.height = image.naturalHeight || image.height;
        const outputCtx = canvasContext2d(outputCanvas);
        outputCtx.clearRect(0, 0, outputCanvas.width, outputCanvas.height);
        outputCtx.drawImage(image, 0, 0);
        sizeLabel.textContent = `${outputCanvas.width} x ${outputCanvas.height}`;
        emptyState.style.display = "none";
        resolve(true);
      };
      image.onerror = () => resolve(false);
      image.src = dataUrl;
    });
  }
  async function restorePixelStateFromCache(state) {
    if (!state || state.isGif || !state.outputDataUrl) {
      return false;
    }
    applyPixelControls(state.controls);
    updateRangeDisplay();
    const restored = await drawOutputCanvasFromDataUrl(state.outputDataUrl);
    if (!restored) {
      return false;
    }
    isGif = false;
    updateSaveButtonLabel();
    if (previewModal.isOpen) {
      previewModal.update(outputCanvas);
    }
    return true;
  }
  function addFilesToQueue(entries, sourceLabel) {
    const source = sourceLabel || "\u0438\u0441\u0442\u043E\u0447\u043D\u0438\u043A\u0430";
    const deduped = coreFiles.dedupeFileEntries(entries || []);
    const existingKeys = new Set(batchQueue.map((item) => item.key));
    let added = 0;
    let skipped = 0;
    let firstAdded = null;
    for (const entry of deduped) {
      if (!entry || !entry.file) continue;
      if (!coreFiles.isImageFile(entry.file)) {
        skipped += 1;
        continue;
      }
      const normalizedPath = normalizeQueuePath(entry.file, entry.relativePath);
      const key = makeQueueKey(entry.file, normalizedPath);
      if (existingKeys.has(key)) {
        skipped += 1;
        continue;
      }
      const item = {
        file: entry.file,
        relativePath: normalizedPath,
        key,
        savedState: null
      };
      if (!firstAdded) {
        firstAdded = item;
      }
      batchQueue.push(item);
      existingKeys.add(key);
      added += 1;
    }
    if (!added) {
      renderQueueList();
      updateQueueSummary();
      updateBatchButtons();
      if (skipped > 0) {
        alert("\u041D\u043E\u0432\u044B\u0445 \u043F\u043E\u0434\u0445\u043E\u0434\u044F\u0449\u0438\u0445 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439 \u043D\u0435 \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u043E.");
      }
      return;
    }
    if (firstAdded) {
      if (batchActiveKey && batchActiveKey !== firstAdded.key) {
        saveActiveQueueItemState();
      }
      batchActiveKey = firstAdded.key;
      if (firstAdded.savedState && !firstAdded.savedState.isGif) {
        handleFile(firstAdded.file, {
          restoreState: firstAdded.savedState
        });
      } else {
        handleFile(firstAdded.file);
      }
    }
    renderQueueList();
    updateQueueSummary();
    updateBatchButtons();
    if (skipped > 0) {
      console.info(`\u0414\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u043E ${added} \u0444\u0430\u0439\u043B(\u043E\u0432) \u0438\u0437 ${source}. \u041F\u0440\u043E\u043F\u0443\u0449\u0435\u043D\u043E: ${skipped}.`);
    }
  }
  function removeActiveQueueItem() {
    if (!batchQueue.length) return false;
    let index = batchQueue.findIndex((item) => item.key === batchActiveKey);
    if (index < 0 && currentFile) {
      index = batchQueue.findIndex((item) => item.file === currentFile);
    }
    if (index < 0) return false;
    batchQueue.splice(index, 1);
    if (!batchQueue.length) {
      batchActiveKey = "";
      clearCurrentImageState();
      renderQueueList();
      updateBatchButtons();
      return true;
    }
    const nextIndex = Math.min(index, batchQueue.length - 1);
    const nextItem = batchQueue[nextIndex];
    if (!nextItem) return false;
    batchActiveKey = nextItem.key;
    if (nextItem.savedState && !nextItem.savedState.isGif) {
      handleFile(nextItem.file, {
        restoreState: nextItem.savedState
      });
    } else {
      handleFile(nextItem.file);
    }
    renderQueueList();
    updateQueueSummary();
    updateBatchButtons();
    return true;
  }
  function removeQueueItemByKey(key) {
    if (!key || !batchQueue.length) return false;
    const index = batchQueue.findIndex((item) => item.key === key);
    if (index < 0) return false;
    const removed = batchQueue[index];
    if (!removed) return false;
    batchQueue.splice(index, 1);
    if (!batchQueue.length) {
      batchActiveKey = "";
      clearCurrentImageState();
      renderQueueList();
      updateBatchButtons();
      return true;
    }
    if (removed.key === batchActiveKey) {
      const nextIndex = Math.min(index, batchQueue.length - 1);
      const nextItem = batchQueue[nextIndex];
      if (!nextItem) return false;
      batchActiveKey = nextItem.key;
      if (nextItem.savedState && !nextItem.savedState.isGif) {
        handleFile(nextItem.file, {
          restoreState: nextItem.savedState
        });
      } else {
        handleFile(nextItem.file);
      }
    } else {
      renderQueueList();
      updateQueueSummary();
      updateBatchButtons();
    }
    return true;
  }
  function clearQueue() {
    batchQueue = [];
    batchActiveKey = "";
    clearCurrentImageState();
    renderQueueList();
    updateBatchButtons();
  }
  function selectQueueItemByKey(key) {
    if (!key) return;
    const item = batchQueue.find((entry) => entry.key === key);
    if (!item) return;
    if (item.key === batchActiveKey) return;
    if (batchActiveKey) {
      saveActiveQueueItemState();
    }
    batchActiveKey = item.key;
    renderQueueList();
    updateQueueSummary();
    if (item.savedState && !item.savedState.isGif) {
      handleFile(item.file, {
        restoreState: item.savedState
      });
    } else {
      handleFile(item.file);
    }
  }
  function stopGifLoop() {
    if (gifLoopId) {
      cancelAnimationFrame(gifLoopId);
      gifLoopId = null;
    }
    gifLastFrameTime = 0;
  }
  function resetGifState() {
    stopGifLoop();
    gifFrames = null;
    gifFrameIndex = 0;
    gifFrameElapsed = 0;
    gifLastFrameTime = 0;
  }
  function renderGifFrame(frame) {
    if (!frame || !frame.canvas) return;
    const size = renderToCanvas(frame.canvas, outputCanvas);
    if (size) {
      sizeLabel.textContent = `${size.width} x ${size.height}`;
    }
    emptyState.style.display = "none";
    if (previewModal.isOpen) {
      previewModal.update(outputCanvas);
    }
  }
  function startGifLoop() {
    if (!isGif || !gifFrames || gifFrames.length === 0) return;
    stopGifLoop();
    gifFrameIndex = gifFrameIndex % gifFrames.length;
    gifFrameElapsed = 0;
    const initialFrame = gifFrames[gifFrameIndex];
    if (!initialFrame) return;
    renderGifFrame(initialFrame);
    const tick = (timestamp) => {
      if (!isGif || !gifFrames || gifFrames.length === 0) {
        stopGifLoop();
        return;
      }
      if (!gifLastFrameTime) {
        gifLastFrameTime = timestamp;
      }
      let delta = timestamp - gifLastFrameTime;
      gifLastFrameTime = timestamp;
      if (delta < 0) delta = 0;
      gifFrameElapsed += delta;
      let safety = 0;
      while (safety < gifFrames.length * 2) {
        const currentFrame = gifFrames[gifFrameIndex];
        if (!currentFrame) break;
        const currentDelay = Math.max(currentFrame.delay || GIF_FRAME_INTERVAL, GIF_FRAME_INTERVAL);
        if (gifFrameElapsed < currentDelay) break;
        gifFrameElapsed -= currentDelay;
        gifFrameIndex = (gifFrameIndex + 1) % gifFrames.length;
        safety += 1;
      }
      const frame = gifFrames[gifFrameIndex];
      if (frame) {
        renderGifFrame(frame);
      }
      gifLoopId = requestAnimationFrame(tick);
    };
    gifLoopId = requestAnimationFrame(tick);
  }
  async function saveRetroGif() {
    if (!isGif || !currentFile) {
      alert("\u0422\u0435\u043A\u0443\u0449\u0438\u0439 \u0444\u0430\u0439\u043B \u043D\u0435 GIF.");
      return;
    }
    if (!gifFrames || gifFrames.length === 0) {
      try {
        const token = gifDecodeToken;
        const frames = await loadGifFrames(currentFile, token);
        if (token === gifDecodeToken && frames && frames.length) {
          gifFrames = frames;
        }
      } catch (err) {
        console.warn(err);
      }
    }
    if (!gifFrames || gifFrames.length === 0) {
      alert("\u041A\u0430\u0434\u0440\u044B GIF \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u043D\u044B. \u041D\u0443\u0436\u0435\u043D ImageDecoder \u0438\u043B\u0438 gifuct.js.");
      return;
    }
    const previousLabel = saveBtn.textContent;
    const wasGifLoopRunning = !!gifLoopId;
    if (wasGifLoopRunning) {
      stopGifLoop();
    }
    setSaveButtonState("GIF 0%", true);
    try {
      const GIF = await coreGifEncode.loadGifJs(GIF_JS_URL);
      const encoder = new GIF({
        workers: Math.min(4, Math.max(2, navigator.hardwareConcurrency || 2)),
        quality: 10,
        workerScript: coreGifEncode.resolveWorkerScriptUrl(GIF_WORKER_URL),
        background: "#000",
        repeat: 0
      });
      const frameCanvases = gifFrames.map((frame) => renderFrameCanvas(frame.canvas));
      frameCanvases.forEach((canvas, index) => {
        const sourceFrame = gifFrames?.[index];
        if (!sourceFrame) return;
        encoder.addFrame(canvas, {
          delay: Math.round(sourceFrame.delay || GIF_FRAME_INTERVAL),
          copy: true
        });
      });
      encoder.on("progress", (progress) => {
        const percent = Math.round(progress * 100);
        setSaveButtonState(`GIF ${percent}%`, true);
      });
      encoder.on("finished", (blob) => {
        const baseName = currentFileName ? currentFileName.replace(/\\.[^.]+$/, "") : "retro_pixel";
        const link = document.createElement("a");
        link.download = `${baseName}.gif`;
        link.href = URL.createObjectURL(blob);
        link.click();
        URL.revokeObjectURL(link.href);
        setSaveButtonState(previousLabel || "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C GIF", false);
        updateSaveButtonLabel();
        if (wasGifLoopRunning) startGifLoop();
      });
      encoder.render();
    } catch (err) {
      console.error(err);
      alert(errorMessage(err, "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C GIF."));
      setSaveButtonState(previousLabel || "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C GIF", false);
      updateSaveButtonLabel();
      if (wasGifLoopRunning) startGifLoop();
    }
  }
  var bayer4 = [
    [
      0,
      8,
      2,
      10
    ],
    [
      12,
      4,
      14,
      6
    ],
    [
      3,
      11,
      1,
      9
    ],
    [
      15,
      7,
      13,
      5
    ]
  ];
  var DITHER_KERNELS = {
    floyd: [
      [
        1,
        0,
        7 / 16
      ],
      [
        -1,
        1,
        3 / 16
      ],
      [
        0,
        1,
        5 / 16
      ],
      [
        1,
        1,
        1 / 16
      ]
    ],
    atkinson: [
      [
        1,
        0,
        1 / 8
      ],
      [
        2,
        0,
        1 / 8
      ],
      [
        -1,
        1,
        1 / 8
      ],
      [
        0,
        1,
        1 / 8
      ],
      [
        1,
        1,
        1 / 8
      ],
      [
        0,
        2,
        1 / 8
      ]
    ],
    jjn: [
      [
        1,
        0,
        7 / 48
      ],
      [
        2,
        0,
        5 / 48
      ],
      [
        -2,
        1,
        3 / 48
      ],
      [
        -1,
        1,
        5 / 48
      ],
      [
        0,
        1,
        7 / 48
      ],
      [
        1,
        1,
        5 / 48
      ],
      [
        2,
        1,
        3 / 48
      ],
      [
        -2,
        2,
        1 / 48
      ],
      [
        -1,
        2,
        3 / 48
      ],
      [
        0,
        2,
        5 / 48
      ],
      [
        1,
        2,
        3 / 48
      ],
      [
        2,
        2,
        1 / 48
      ]
    ]
  };
  var ORIGINAL_DITHER_LEVELS = 4;
  function buildUniformPalette(levelsPerChannel) {
    const palette = [];
    if (levelsPerChannel <= 1) {
      return [
        [
          0,
          0,
          0
        ]
      ];
    }
    const step = 255 / (levelsPerChannel - 1);
    for (let r = 0; r < levelsPerChannel; r += 1) {
      for (let g = 0; g < levelsPerChannel; g += 1) {
        for (let b = 0; b < levelsPerChannel; b += 1) {
          palette.push([
            Math.round(r * step),
            Math.round(g * step),
            Math.round(b * step)
          ]);
        }
      }
    }
    return palette;
  }
  var ORIGINAL_DITHER_PALETTE = buildUniformPalette(ORIGINAL_DITHER_LEVELS);
  function clamp(value) {
    return Math.max(0, Math.min(255, value));
  }
  function applyAdjustments(data) {
    const b = Number(brightness.value);
    const c = Number(contrast.value);
    const s = Number(saturation.value) / 100;
    const contrastFactor = 259 * (c + 255) / (255 * (259 - c));
    for (let i = 0; i < data.length; i += 4) {
      let r = data[i] ?? 0;
      let g = data[i + 1] ?? 0;
      let bch = data[i + 2] ?? 0;
      r = contrastFactor * (r - 128) + 128 + b;
      g = contrastFactor * (g - 128) + 128 + b;
      bch = contrastFactor * (bch - 128) + 128 + b;
      const gray = 0.3 * r + 0.59 * g + 0.11 * bch;
      r = gray + (r - gray) * s;
      g = gray + (g - gray) * s;
      bch = gray + (bch - gray) * s;
      data[i] = clamp(r);
      data[i + 1] = clamp(g);
      data[i + 2] = clamp(bch);
    }
  }
  function applyNoise(data) {
    const noiseAmount = Number(noise.value);
    if (noiseAmount > 0) {
      for (let i = 0; i < data.length; i += 4) {
        const n = (Math.random() * 2 - 1) * noiseAmount;
        data[i] = clamp((data[i] ?? 0) + n);
        data[i + 1] = clamp((data[i + 1] ?? 0) + n);
        data[i + 2] = clamp((data[i + 2] ?? 0) + n);
      }
    }
  }
  function applyScanlines(data, width, height) {
    for (let y = 0; y < height; y += 2) {
      for (let x = 0; x < width; x += 1) {
        const idx = (y * width + x) * 4;
        data[idx] = (data[idx] ?? 0) * 0.85;
        data[idx + 1] = (data[idx + 1] ?? 0) * 0.85;
        data[idx + 2] = (data[idx + 2] ?? 0) * 0.85;
      }
    }
  }
  function applyAlphaThreshold(data) {
    for (let i = 3; i < data.length; i += 4) {
      data[i] = (data[i] ?? 0) >= 128 ? 255 : 0;
    }
  }
  function forceOpaqueAlpha(data) {
    for (let i = 3; i < data.length; i += 4) {
      data[i] = 255;
    }
  }
  function ensureEffectBufferSize(width, height) {
    if (effectBufferCanvas.width !== width || effectBufferCanvas.height !== height) {
      effectBufferCanvas.width = width;
      effectBufferCanvas.height = height;
    } else {
      effectBufferCtx.clearRect(0, 0, width, height);
    }
  }
  function applyCrtGlow(targetCtx, width, height) {
    ensureEffectBufferSize(width, height);
    effectBufferCtx.drawImage(targetCtx.canvas, 0, 0, width, height);
    targetCtx.save();
    targetCtx.globalCompositeOperation = "screen";
    targetCtx.globalAlpha = 0.24;
    targetCtx.filter = "blur(1.8px)";
    targetCtx.drawImage(effectBufferCanvas, 0, 0, width, height);
    targetCtx.restore();
  }
  function drawPixelGrid(targetCtx, width, height, cellsX, cellsY) {
    if (cellsX < 2 && cellsY < 2) return;
    const stepX = width / cellsX;
    const stepY = height / cellsY;
    targetCtx.save();
    targetCtx.strokeStyle = "rgba(0, 0, 0, 0.28)";
    targetCtx.lineWidth = 1;
    targetCtx.beginPath();
    for (let x = 1; x < cellsX; x += 1) {
      const px = Math.round(x * stepX) + 0.5;
      targetCtx.moveTo(px, 0);
      targetCtx.lineTo(px, height);
    }
    for (let y = 1; y < cellsY; y += 1) {
      const py = Math.round(y * stepY) + 0.5;
      targetCtx.moveTo(0, py);
      targetCtx.lineTo(width, py);
    }
    targetCtx.stroke();
    targetCtx.restore();
  }
  function findNearestColor(r, g, b, palette) {
    let best = palette[0] ?? [
      0,
      0,
      0
    ];
    let bestDist = Number.MAX_VALUE;
    for (const color of palette) {
      const dr = r - color[0];
      const dg = g - color[1];
      const db = b - color[2];
      const dist = dr * dr + dg * dg + db * db;
      if (dist < bestDist) {
        bestDist = dist;
        best = color;
      }
    }
    return best;
  }
  function applyErrorDiffusionDither(data, width, height, palette, kernel) {
    const pixelCount = width * height;
    const requiredSize = pixelCount * 3;
    if (ditherBuffer.length < requiredSize) {
      ditherBuffer = new Float32Array(requiredSize);
    }
    const buffer = ditherBuffer;
    for (let src = 0, dst = 0; src < data.length; src += 4, dst += 3) {
      buffer[dst] = data[src] ?? 0;
      buffer[dst + 1] = data[src + 1] ?? 0;
      buffer[dst + 2] = data[src + 2] ?? 0;
    }
    for (let y = 0; y < height; y += 1) {
      for (let x = 0; x < width; x += 1) {
        const pixelIndex = y * width + x;
        const i4 = pixelIndex * 4;
        if ((data[i4 + 3] ?? 0) === 0) continue;
        const i3 = pixelIndex * 3;
        const r = clamp(buffer[i3] ?? 0);
        const g = clamp(buffer[i3 + 1] ?? 0);
        const b = clamp(buffer[i3 + 2] ?? 0);
        const [nr, ng, nb] = findNearestColor(r, g, b, palette);
        data[i4] = nr;
        data[i4 + 1] = ng;
        data[i4 + 2] = nb;
        const errR = r - nr;
        const errG = g - ng;
        const errB = b - nb;
        if (errR === 0 && errG === 0 && errB === 0) continue;
        for (const [dx, dy, weight] of kernel) {
          const nx = x + dx;
          const ny = y + dy;
          if (nx < 0 || nx >= width || ny < 0 || ny >= height) continue;
          const neighborIndex = ny * width + nx;
          const n4 = neighborIndex * 4;
          if ((data[n4 + 3] ?? 0) === 0) continue;
          const n3 = neighborIndex * 3;
          buffer[n3] = (buffer[n3] ?? 0) + errR * weight;
          buffer[n3 + 1] = (buffer[n3 + 1] ?? 0) + errG * weight;
          buffer[n3 + 2] = (buffer[n3 + 2] ?? 0) + errB * weight;
        }
      }
    }
  }
  function applyPalette(data, width, height) {
    const paletteKey = paletteSelect.value;
    const dither = ditherSelect.value;
    let palette = palettes[paletteKey];
    if (!palette) {
      if (dither === "none") return;
      palette = ORIGINAL_DITHER_PALETTE;
    }
    const errorDiffusionKernel = DITHER_KERNELS[dither];
    if (errorDiffusionKernel) {
      applyErrorDiffusionDither(data, width, height, palette, errorDiffusionKernel);
      return;
    }
    for (let y = 0; y < height; y += 1) {
      for (let x = 0; x < width; x += 1) {
        const idx = (y * width + x) * 4;
        let r = data[idx] ?? 0;
        let g = data[idx + 1] ?? 0;
        let b = data[idx + 2] ?? 0;
        if (dither === "ordered") {
          const threshold = ((bayer4[y % 4]?.[x % 4] ?? 0) - 7.5) * 3;
          r = clamp(r + threshold);
          g = clamp(g + threshold);
          b = clamp(b + threshold);
        }
        const [nr, ng, nb] = findNearestColor(r, g, b, palette);
        data[idx] = nr;
        data[idx + 1] = ng;
        data[idx + 2] = nb;
      }
    }
  }
  function renderToCanvas(source, targetCanvas) {
    if (!source || !targetCanvas) return null;
    const maxDim = 1400;
    const pixel = Number(pixelSize.value);
    const sourceWidth = source instanceof HTMLImageElement ? source.naturalWidth || source.width : source.width;
    const sourceHeight = source instanceof HTMLImageElement ? source.naturalHeight || source.height : source.height;
    const scale = Math.min(1, maxDim / Math.max(sourceWidth, sourceHeight));
    const targetWidth = Math.max(1, Math.round(sourceWidth * scale));
    const targetHeight = Math.max(1, Math.round(sourceHeight * scale));
    const smallWidth = Math.max(1, Math.round(targetWidth / pixel));
    const smallHeight = Math.max(1, Math.round(targetHeight / pixel));
    if (downscaleCanvas.width !== smallWidth || downscaleCanvas.height !== smallHeight) {
      downscaleCanvas.width = smallWidth;
      downscaleCanvas.height = smallHeight;
    } else {
      downscaleCtx.clearRect(0, 0, smallWidth, smallHeight);
    }
    downscaleCtx.imageSmoothingEnabled = true;
    downscaleCtx.drawImage(source, 0, 0, smallWidth, smallHeight);
    const smallImgData = downscaleCtx.getImageData(0, 0, smallWidth, smallHeight);
    const smallData = smallImgData.data;
    applyAdjustments(smallData);
    applyPalette(smallData, smallWidth, smallHeight);
    applyNoise(smallData);
    if (preserveAlpha.checked) {
      if (alphaThreshold.checked) {
        applyAlphaThreshold(smallData);
      }
    } else {
      forceOpaqueAlpha(smallData);
    }
    downscaleCtx.putImageData(smallImgData, 0, 0);
    targetCanvas.width = targetWidth;
    targetCanvas.height = targetHeight;
    const targetCtx = canvasContext2d(targetCanvas);
    targetCtx.imageSmoothingEnabled = false;
    targetCtx.clearRect(0, 0, targetWidth, targetHeight);
    targetCtx.drawImage(downscaleCanvas, 0, 0, targetWidth, targetHeight);
    if (scanlines.checked) {
      const targetImgData = targetCtx.getImageData(0, 0, targetWidth, targetHeight);
      applyScanlines(targetImgData.data, targetWidth, targetHeight);
      targetCtx.putImageData(targetImgData, 0, 0);
    }
    if (crtGlow.checked) {
      applyCrtGlow(targetCtx, targetWidth, targetHeight);
    }
    if (pixelGrid.checked) {
      drawPixelGrid(targetCtx, targetWidth, targetHeight, smallWidth, smallHeight);
    }
    return {
      width: targetWidth,
      height: targetHeight
    };
  }
  function renderFrameCanvas(source) {
    const frameCanvas = document.createElement("canvas");
    renderToCanvas(source, frameCanvas);
    return frameCanvas;
  }
  function render() {
    if (!sourceImage) return;
    if (isGif && gifFrames && gifFrames.length) {
      const frame = gifFrames[gifFrameIndex];
      if (frame) {
        renderGifFrame(frame);
      }
      return;
    }
    const size = renderToCanvas(sourceImage, outputCanvas);
    if (size) {
      sizeLabel.textContent = `${size.width} x ${size.height}`;
    }
    emptyState.style.display = "none";
    if (previewModal.isOpen) {
      previewModal.update(outputCanvas);
    }
  }
  function scheduleRender() {
    if (renderRequestId !== null) return;
    renderRequestId = requestAnimationFrame(() => {
      renderRequestId = null;
      render();
    });
  }
  function showOriginalPreview(src, onload) {
    corePreview.show({
      previewImg,
      originalPreview,
      placeholder: dropZonePlaceholder,
      src,
      onload
    });
  }
  function clearPreview() {
    corePreview.clear({
      previewImg,
      originalPreview,
      placeholder: dropZonePlaceholder
    });
  }
  function updateRangeDisplay() {
    pixelValue.textContent = `${pixelSize.value}px`;
    brightnessValue.textContent = brightness.value;
    contrastValue.textContent = contrast.value;
    saturationValue.textContent = `${saturation.value}%`;
    noiseValue.textContent = noise.value;
  }
  async function handleFile(file, options = {}) {
    if (!file) return;
    const restoreState = options.restoreState ?? null;
    const isImage = file.type ? file.type.startsWith("image/") : coreFiles.isImageFile(file);
    if (!isImage) {
      alert("\u041F\u043E\u0436\u0430\u043B\u0443\u0439\u0441\u0442\u0430, \u0432\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435");
      return;
    }
    sourceImage = null;
    resetGifState();
    gifDecodeToken += 1;
    const token = gifDecodeToken;
    const gifCheckPromise = coreGifDecode.isGifFile(file).catch(() => false);
    const probableGif = looksLikeGif(file);
    isGif = false;
    currentFile = file;
    currentFileName = file.name || "";
    syncActiveQueueWithFile(file);
    updateSaveButtonLabel();
    if (currentObjectUrl) {
      URL.revokeObjectURL(currentObjectUrl);
      currentObjectUrl = null;
    }
    const objectUrl = URL.createObjectURL(file);
    currentObjectUrl = objectUrl;
    showOriginalPreview(objectUrl, async () => {
      if (token !== gifDecodeToken) return;
      sourceImage = previewImg;
      updateQueueSummary();
      if (restoreState && typeof restorePixelStateFromCache === "function") {
        const restored = await restorePixelStateFromCache(restoreState);
        if (token !== gifDecodeToken) return;
        if (restored) {
          return;
        }
      }
      const renderedStaticPreview = !probableGif;
      if (renderedStaticPreview) {
        render();
      }
      const detectedGif = await gifCheckPromise;
      if (token !== gifDecodeToken) return;
      isGif = detectedGif;
      updateSaveButtonLabel();
      if (!renderedStaticPreview || isGif) {
        render();
      }
      if (isGif) {
        loadGifFrames(file, token).then((frames) => {
          if (token !== gifDecodeToken) return;
          gifFrames = frames;
          gifFrameIndex = 0;
          gifFrameElapsed = 0;
          startGifLoop();
        });
      }
    });
  }
  coreIngestUi.bindIngestControls({
    fileInput: imageInput,
    folderInput,
    dropZone,
    pickFilesBtn,
    pickFolderBtn,
    clearQueueBtn,
    ignoreSelector: ".icon-btn",
    isBusy: () => batchBusy,
    onEntries: (entries, sourceLabel) => {
      addFilesToQueue(entries, sourceLabel);
    },
    onFile: (file) => {
      void handleFile(file);
    },
    onClear: clearQueue
  });
  [
    pixelSize,
    paletteSelect,
    ditherSelect,
    brightness,
    contrast,
    saturation,
    noise,
    scanlines,
    preserveAlpha,
    crtGlow,
    pixelGrid,
    alphaThreshold
  ].forEach((control) => {
    control.addEventListener("input", () => {
      updateRangeDisplay();
      scheduleRender();
    });
  });
  function savePng() {
    const link = document.createElement("a");
    link.download = `retro-pixel-${Date.now()}.png`;
    link.href = outputCanvas.toDataURL("image/png");
    link.click();
  }
  async function createRetroPngBlobForFile(file) {
    const image = await coreFiles.loadImageFromFile(file);
    const canvas = document.createElement("canvas");
    renderToCanvas(image, canvas);
    return coreZip.canvasToPngBlob(canvas);
  }
  function buildRetroZipEntryName(queueItem) {
    const tools = coreFiles;
    const relativePath = tools.normalizePath(queueItem.relativePath || queueItem.file.name);
    const segments = relativePath.split("/");
    if (segments.length > 1) {
      segments.pop();
    } else {
      segments.length = 0;
    }
    const dir = segments.join("/");
    const outputFileName = `${tools.baseName(queueItem.file.name)}-retro.png`;
    return dir ? tools.sanitizePath(`${dir}/${outputFileName}`) : tools.sanitizePath(outputFileName);
  }
  async function saveZip() {
    const queueItems = getBatchQueueItems();
    if (!queueItems.length) {
      alert("\u041E\u0447\u0435\u0440\u0435\u0434\u044C \u043F\u0443\u0441\u0442\u0430. \u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 \u0444\u0430\u0439\u043B\u044B \u0438\u043B\u0438 \u043F\u0430\u043F\u043A\u0443.");
      return;
    }
    const originalLabel = saveZipBtn.textContent;
    const entries = [];
    const total = queueItems.length;
    let failed = 0;
    const wasGifLoopRunning = Boolean(gifLoopId);
    setBatchBusy(true);
    if (wasGifLoopRunning) {
      stopGifLoop();
    }
    try {
      let index = 0;
      for (const queueItem of queueItems) {
        coreIngestUi.setZipButtonProgress(saveZipBtn, index + 1, total);
        try {
          const pngBlob = await createRetroPngBlobForFile(queueItem.file);
          const bytes = new Uint8Array(await pngBlob.arrayBuffer());
          entries.push({
            name: buildRetroZipEntryName(queueItem),
            bytes
          });
        } catch (err) {
          failed += 1;
          console.error(err);
        }
        index += 1;
      }
      if (!entries.length) {
        alert("\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u0444\u043E\u0440\u043C\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043D\u0438 \u043E\u0434\u043D\u043E\u0433\u043E \u0444\u0430\u0439\u043B\u0430 \u0434\u043B\u044F \u0430\u0440\u0445\u0438\u0432\u0430.");
        return;
      }
      const uniqueEntries = coreZip.ensureUniqueEntryNames(entries);
      const zipBlob = coreZip.buildZipBlob(uniqueEntries);
      const zipName = `retro-batch-${coreZip.formatDateStamp(/* @__PURE__ */ new Date())}.zip`;
      coreZip.triggerDownload(zipBlob, zipName);
      if (failed > 0) {
        alert(`\u0410\u0440\u0445\u0438\u0432 \u0441\u043E\u0437\u0434\u0430\u043D. \u0423\u0441\u043F\u0435\u0448\u043D\u043E: ${entries.length}, \u043E\u0448\u0438\u0431\u043E\u043A: ${failed}.`);
      }
    } finally {
      coreIngestUi.resetZipButtonLabel(saveZipBtn, originalLabel || "\u0421\u043A\u0430\u0447\u0430\u0442\u044C \u0432\u0441\u0435 (.zip)");
      setBatchBusy(false);
      if (sourceImage) {
        scheduleRender();
      }
      if (wasGifLoopRunning && isGif) {
        startGifLoop();
      }
    }
  }
  coreIngestUi.bindQueueList({
    queueList,
    isBusy: () => batchBusy,
    onRemove: (key) => {
      removeQueueItemByKey(key);
    },
    onSelect: (key) => {
      selectQueueItemByKey(key);
    }
  });
  saveBtn.addEventListener("click", () => {
    if (!sourceImage) return;
    if (isGif) {
      saveRetroGif();
      return;
    }
    savePng();
  });
  saveZipBtn.addEventListener("click", () => {
    void saveZip();
  });
  removeBtn.addEventListener("click", (event) => {
    event.stopPropagation();
    if (removeActiveQueueItem()) {
      return;
    }
    clearCurrentImageState();
  });
  updateRangeDisplay();
  updateSaveButtonLabel();
  renderQueueList();
  updateQueueSummary();
  updateBatchButtons();
  outputCanvas.addEventListener("click", () => {
    if (!sourceImage || !outputCanvas.width || !outputCanvas.height) {
      alert("\u0421\u043D\u0430\u0447\u0430\u043B\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435!");
      return;
    }
    previewModal.open(outputCanvas);
  });
})();
