interface BuildEntry {
  readonly source: string;
  readonly output: string;
}

const entries: readonly BuildEntry[] = [
  { source: "src/shared/js/embed-flag.ts", output: "shared/js/embed-flag.js" },
  { source: "src/shared/js/i18n.ts", output: "shared/js/i18n.js" },
  { source: "src/shared/js/app-core.ts", output: "shared/js/app-core.js" },
  { source: "src/shared/js/shell-tabs.ts", output: "shared/js/shell-tabs.js" },
  { source: "src/projects/ascii-convert/app.ts", output: "projects/ascii-convert/app.js" },
  { source: "src/projects/image-resize/app.ts", output: "projects/image-resize/app.js" },
  { source: "src/projects/retro-pixel/app.ts", output: "projects/retro-pixel/app.js" },
];

const generatedBanner = (source: string): string =>
  [
    `// Generated by deno task build from ${source}.`,
    "// Do not edit this file directly; edit the TypeScript source instead.",
    "",
  ].join("\n");

async function bundleEntry(entry: BuildEntry): Promise<void> {
  const command = new Deno.Command(Deno.execPath(), {
    args: [
      "bundle",
      "--quiet",
      "--no-check",
      "--platform",
      "browser",
      "--format",
      "iife",
      entry.source,
    ],
    stdout: "piped",
    stderr: "piped",
  });

  const { code, stdout, stderr } = await command.output();
  if (code !== 0) {
    const message = new TextDecoder().decode(stderr).trim();
    throw new Error(`Failed to bundle ${entry.source}: ${message}`);
  }

  const bundle = new TextDecoder().decode(stdout);
  await Deno.writeTextFile(entry.output, `${generatedBanner(entry.source)}${bundle}`);
  console.log(`${entry.source} -> ${entry.output}`);
}

for (const entry of entries) {
  await bundleEntry(entry);
}
