// Generated by deno task build from src/shared/js/embed-flag.ts.
// Do not edit this file directly; edit the TypeScript source instead.
(() => {
  // src/shared/js/embed-flag.ts
  (function initEmbedFlag() {
    const params = new URLSearchParams(window.location.search);
    if (params.get("embed") === "1") {
      document.documentElement.classList.add("embedded");
    }
  })();
})();
