// Generated by deno task build from src/shared/js/i18n.ts.
// Do not edit this file directly; edit the TypeScript source instead.
(() => {
  // src/shared/js/i18n.ts
  (function initAppI18n() {
    const LANG_EN = "en";
    const LANG_RU = "ru";
    function detectLanguage() {
      const candidates = [];
      if (Array.isArray(navigator.languages)) {
        candidates.push(...navigator.languages);
      }
      if (navigator.language) {
        candidates.push(navigator.language);
      }
      for (const value of candidates) {
        if (/^en\b/i.test(String(value || ""))) {
          return LANG_EN;
        }
      }
      return LANG_RU;
    }
    const lang = detectLanguage();
    const isEnglish = lang === LANG_EN;
    document.documentElement.setAttribute("lang", lang);
    const RU_TO_EN = {
      "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442": "Choose a tool",
      "\u0414\u0432\u0435 \u0443\u0442\u0438\u043B\u0438\u0442\u044B \u0432 \u043E\u0434\u043D\u043E\u043C \u043C\u0435\u0441\u0442\u0435:": "Two tools in one place:",
      "ASCII-\u043A\u043E\u043D\u0432\u0435\u0440\u0442\u0435\u0440 \u0438 \u0440\u0435\u0442\u0440\u043E-\u043F\u0438\u043A\u0441\u0435\u043B\u044C\u043D\u044B\u0439 \u043A\u043E\u043D\u0432\u0435\u0440\u0442\u0435\u0440.": "ASCII converter and retro pixel converter.",
      "\u041D\u0430\u0431\u043E\u0440 \u0433\u043E\u0442\u043E\u0432": "Toolset ready",
      "\u041F\u0440\u0435\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F \u0432 ASCII-\u0433\u0440\u0430\u0444\u0438\u043A\u0443, \u043F\u043E\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u0435\u0442 \u043D\u0430\u0431\u043E\u0440\u044B \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432 \u0438": "Converts images to ASCII art, supports character sets and",
      "\u044D\u043A\u0441\u043F\u043E\u0440\u0442.": "export.",
      "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u2192": "Open \u2192",
      "\u041A\u043E\u043D\u0432\u0435\u0440\u0442\u0435\u0440 \u0432 \u043F\u0438\u043A\u0441\u0435\u043B\u044C-\u0430\u0440\u0442 \u0441 \u0440\u0435\u0442\u0440\u043E-\u043F\u0440\u0435\u0434\u0443\u0441\u0442\u0430\u043D\u043E\u0432\u043A\u0430\u043C\u0438, \u0448\u0443\u043C\u043E\u043C \u0438 \u0441\u043A\u0430\u043D\u043B\u0430\u0439\u043D\u043E\u043C.": "Pixel-art converter with retro presets, noise, and scanlines.",
      "\u0444\u0430\u0439\u043B.": "file.",
      "\u0412\u044B\u0431\u0435\u0440\u0438 \u0438\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442 \u0438 \u043F\u0440\u043E\u0434\u043E\u043B\u0436\u0430\u0439 \u0440\u0430\u0431\u043E\u0442\u0443.": "Pick a tool and continue.",
      "ASCII \u041A\u043E\u043D\u0432\u0435\u0440\u0442\u0435\u0440": "ASCII Converter",
      "\u0420\u0435\u0442\u0440\u043E \u041F\u0438\u043A\u0441\u0435\u043B\u044C": "Retro Pixel",
      "PIXEL \u041A\u043E\u043D\u0432\u0435\u0440\u0442\u0435\u0440": "PIXEL Converter",
      "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u043F\u0430\u043D\u0435\u043B\u044C \u043D\u0430\u0441\u0442\u0440\u043E\u0435\u043A": "Open settings panel",
      "\u0417\u0430\u043A\u0440\u044B\u0442\u044C \u043F\u0430\u043D\u0435\u043B\u044C \u043D\u0430\u0441\u0442\u0440\u043E\u0435\u043A": "Close settings panel",
      "\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435:": "Image:",
      "\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435": "Image",
      "\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F \u0438\u043B\u0438 \u043F\u0430\u043F\u043A\u0430": "Images or folder",
      "\u041E\u0440\u0438\u0433\u0438\u043D\u0430\u043B": "Original",
      "\u041E\u0440\u0438\u0433\u0438\u043D\u0430\u043B (\u0432\u044B\u0431\u0440\u0430\u043D\u043D\u044B\u0439 \u0444\u0430\u0439\u043B)": "Original (selected file)",
      "\u0423\u0434\u0430\u043B\u0438\u0442\u044C": "Remove",
      "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0432\u044B\u0431\u0440\u0430\u043D\u043D\u044B\u0439": "Remove selected",
      "\u041F\u0435\u0440\u0435\u0442\u0430\u0449\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435": "Drag an image",
      "\u041F\u0435\u0440\u0435\u0442\u0430\u0449\u0438\u0442\u0435 \u0444\u043E\u0442\u043E/\u043F\u0430\u043F\u043A\u0443": "Drag a photo/folder",
      "\u0438\u043B\u0438 \u043D\u0430\u0436\u043C\u0438\u0442\u0435 \u0434\u043B\u044F \u0432\u044B\u0431\u043E\u0440\u0430": "or click to choose",
      "Ctrl+V \u0434\u043B\u044F \u0432\u0441\u0442\u0430\u0432\u043A\u0438": "Ctrl+V to paste",
      "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0444\u0430\u0439\u043B\u044B": "Add files",
      "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043F\u0430\u043F\u043A\u0443": "Add folder",
      "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C \u043E\u0447\u0435\u0440\u0435\u0434\u044C": "Clear queue",
      "\u041E\u0447\u0435\u0440\u0435\u0434\u044C \u043F\u0443\u0441\u0442\u0430": "Queue is empty",
      "\u041E\u0447\u0435\u0440\u0435\u0434\u044C": "Queue",
      "\u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 \u0444\u0430\u0439\u043B\u044B \u0434\u043B\u044F \u043E\u0431\u0440\u0430\u0431\u043E\u0442\u043A\u0438": "Add files for processing",
      "\u0428\u0438\u0440\u0438\u043D\u0430 (px):": "Width (px):",
      "\u041D\u0430\u0431\u043E\u0440 \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432:": "Character set:",
      "\u041C\u0438\u043D\u0438\u043C\u0443\u043C ( .-+ )": "Minimum ( .-+ )",
      "\u041D\u0435\u0431\u043E\u043B\u044C\u0448\u043E\u0439 ( .:-=+* )": "Small ( .:-=+* )",
      "\u0421\u0440\u0435\u0434\u043D\u0438\u0439 ( .:-=+*iItVYX )": "Medium ( .:-=+*iItVYX )",
      "\u041C\u0430\u043A\u0441\u0438\u043C\u0443\u043C ( .:-=+*iItVYXRBM# )": "Maximum ( .:-=+*iItVYXRBM# )",
      "\u0421\u0432\u043E\u0439 \u043D\u0430\u0431\u043E\u0440...": "Custom set...",
      "\u0421\u0438\u043C\u0432\u043E\u043B\u044B \u043E\u0442 \u0442\u0435\u043C\u043D\u043E\u0433\u043E \u043A \u0441\u0432\u0435\u0442\u043B\u043E\u043C\u0443": "Characters from dark to light",
      "\u0426\u0432\u0435\u0442:": "Color:",
      "\u0426\u0432\u0435\u0442\u043D\u043E\u0439 (PNG)": "Color (PNG)",
      "\u041E\u0440\u0430\u043D\u0436\u0435\u0432\u044B\u0439 (Matrix)": "Orange (Matrix)",
      "\u0421\u0435\u0440\u044B\u0439 (\u0422\u0435\u0440\u043C\u0438\u043D\u0430\u043B)": "Gray (Terminal)",
      "* \u0412 \u043F\u0440\u0435\u0432\u044C\u044E \u0431\u0443\u0434\u0435\u0442 \u0431\u0435\u043B\u044B\u043C, \u0432 PNG \u2014 \u0446\u0432\u0435\u0442\u043D\u044B\u043C.": "* White in preview, colored in PNG.",
      "\u0410\u0432\u0442\u043E-\u043A\u043E\u043D\u0442\u0440\u0430\u0441\u0442": "Auto contrast",
      "\u0414\u0438\u0437\u0435\u0440\u0438\u043D\u0433": "Dithering",
      "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C": "Save",
      "\u0421\u043A\u0430\u0447\u0430\u0442\u044C \u0432\u0441\u0435 (.zip)": "Download all (.zip)",
      "\u041A\u043B\u0438\u043A: \u0437\u0443\u043C | \u041B\u041A\u041C: \u043F\u0435\u0440\u0435\u043C\u0435\u0449\u0435\u043D\u0438\u0435 | ESC: \u0437\u0430\u043A\u0440\u044B\u0442\u044C": "Click: zoom | LMB: pan | ESC: close",
      "\u041F\u043E\u0436\u0430\u043B\u0443\u0439\u0441\u0442\u0430, \u0432\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435": "Please select an image",
      "\u0422\u0435\u043A\u0443\u0449\u0438\u0439 \u0444\u0430\u0439\u043B \u043D\u0435 GIF.": "Current file is not a GIF.",
      "\u041A\u0430\u0434\u0440\u044B GIF \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u043D\u044B. \u041D\u0443\u0436\u0435\u043D ImageDecoder \u0438\u043B\u0438 ../../shared/vendor/gifuct.js": "GIF frames are unavailable. ImageDecoder or ../../shared/vendor/gifuct.js is required.",
      "\u041A\u0430\u0434\u0440\u044B GIF \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u043D\u044B. \u041D\u0443\u0436\u0435\u043D ImageDecoder \u0438\u043B\u0438 gifuct.js.": "GIF frames are unavailable. ImageDecoder or gifuct.js is required.",
      "\u041D\u0435\u043A\u043E\u0440\u0440\u0435\u043A\u0442\u043D\u0430\u044F \u0448\u0438\u0440\u0438\u043D\u0430.": "Invalid width.",
      "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C GIF.": "Failed to save GIF.",
      "\u041D\u0435\u0442 \u0434\u0430\u043D\u043D\u044B\u0445 \u0434\u043B\u044F \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u044F!": "No data to save!",
      "\u041D\u0435\u0442 \u0434\u0430\u043D\u043D\u044B\u0445 \u0434\u043B\u044F \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F.": "No data to copy.",
      "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0432 \u0431\u0443\u0444\u0435\u0440 \u043E\u0431\u043C\u0435\u043D\u0430.": "Failed to copy to clipboard.",
      "\u041D\u0435\u043A\u043E\u0440\u0440\u0435\u043A\u0442\u043D\u0430\u044F \u0448\u0438\u0440\u0438\u043D\u0430 \u043A\u043E\u043D\u0432\u0435\u0440\u0442\u0430\u0446\u0438\u0438.": "Invalid conversion width.",
      "\u041E\u0447\u0435\u0440\u0435\u0434\u044C \u043F\u0443\u0441\u0442\u0430. \u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 \u0444\u0430\u0439\u043B\u044B \u0438\u043B\u0438 \u043F\u0430\u043F\u043A\u0443.": "Queue is empty. Add files or a folder.",
      "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u0444\u043E\u0440\u043C\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043D\u0438 \u043E\u0434\u043D\u043E\u0433\u043E \u0444\u0430\u0439\u043B\u0430 \u0434\u043B\u044F \u0430\u0440\u0445\u0438\u0432\u0430.": "Failed to build any files for archive.",
      "\u0421\u043D\u0430\u0447\u0430\u043B\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435!": "Load an image first!",
      "\u041D\u043E\u0432\u044B\u0445 \u043F\u043E\u0434\u0445\u043E\u0434\u044F\u0449\u0438\u0445 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439 \u043D\u0435 \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u043E.": "No new suitable images were added.",
      "\u0424\u0430\u0439\u043B \u043D\u0435 \u0432\u044B\u0431\u0440\u0430\u043D": "No file selected",
      "\u041F\u0430\u043B\u0438\u0442\u0440\u0430": "Palette",
      "\u041F\u0438\u043A\u0441\u0435\u043B\u044C": "Pixel",
      "\u0411\u0435\u0437": "None",
      "\u042F\u0440\u043A\u043E\u0441\u0442\u044C": "Brightness",
      "\u041A\u043E\u043D\u0442\u0440\u0430\u0441\u0442": "Contrast",
      "\u041D\u0430\u0441\u044B\u0449\u0435\u043D\u043D\u043E\u0441\u0442\u044C": "Saturation",
      "\u0428\u0443\u043C": "Noise",
      "\u0421\u043A\u0430\u043D\u043B\u0430\u0439\u043D": "Scanlines",
      "\u041F\u0440\u043E\u0437\u0440\u0430\u0447\u043D\u043E\u0441\u0442\u044C": "Transparency",
      "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C PNG": "Save PNG",
      "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C GIF": "Save GIF",
      "\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435": "Upload an image",
      "\u0424\u0430\u0439\u043B \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043D": "File loaded",
      "\u0432\u044B\u0431\u0440\u0430\u043D": "selected",
      "\u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E": "saved",
      "\u043D\u043E\u0432\u044B\u0439": "new",
      "\u0438\u0441\u0442\u043E\u0447\u043D\u0438\u043A\u0430": "source",
      "\u0432\u044B\u0431\u043E\u0440\u0430 \u0444\u0430\u0439\u043B\u043E\u0432": "file picker",
      "\u0432\u044B\u0431\u043E\u0440\u0430 \u043F\u0430\u043F\u043A\u0438": "folder picker",
      "drag&drop": "drag&drop",
      "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C": "Clear"
    };
    const DYNAMIC_REPLACERS = [
      {
        re: /Файлов в очереди:\s*(\d+)\.\s*Выбран:\s*([^.\n]+)\./g,
        fn: (_m, total, selected) => `Files in queue: ${total}. Selected: ${selected}.`
      },
      {
        re: /Файлов в очереди:\s*(\d+)\./g,
        fn: (_m, total) => `Files in queue: ${total}.`
      },
      {
        re: /Добавлено\s+(\d+)\s+файл\(ов\)\s+из\s+([^.\n]+)\.\s*Пропущено:\s*(\d+)\./g,
        fn: (_m, added, source, skipped) => `Added ${added} file(s) from ${source}. Skipped: ${skipped}.`
      },
      {
        re: /Добавлено\s+(\d+)\s+файл\(ов\)\s+из\s+([^.\n]+)\./g,
        fn: (_m, added, source) => `Added ${added} file(s) from ${source}.`
      },
      {
        re: /Архив создан\.\s*Успешно:\s*(\d+),\s*ошибок:\s*(\d+)\./g,
        fn: (_m, ok, err) => `Archive created. Success: ${ok}, errors: ${err}.`
      }
    ];
    const PHRASES = Object.entries(RU_TO_EN).sort((a, b) => b[0].length - a[0].length);
    const ATTRIBUTE_NAMES = [
      "placeholder",
      "title",
      "aria-label",
      "alt"
    ];
    function hasCyrillic(text) {
      return /[А-Яа-яЁё]/.test(String(text || ""));
    }
    function translateText(text) {
      const original = String(text ?? "");
      if (!isEnglish || !hasCyrillic(original)) {
        return original;
      }
      let output = original;
      for (const [ru, en] of PHRASES) {
        if (output.includes(ru)) {
          output = output.split(ru).join(en);
        }
      }
      for (const { re, fn } of DYNAMIC_REPLACERS) {
        output = output.replace(re, fn);
      }
      return output;
    }
    function interpolate(template, params) {
      if (!params) return template;
      let output = String(template);
      for (const [key, value] of Object.entries(params)) {
        output = output.split(`{${key}}`).join(String(value));
      }
      return output;
    }
    function t(input, params) {
      const prepared = interpolate(String(input ?? ""), params);
      return isEnglish ? translateText(prepared) : prepared;
    }
    function translateTextNode(node) {
      if (!node || node.nodeType !== Node.TEXT_NODE) return;
      if (!node.parentElement) return;
      const tag = node.parentElement.tagName;
      if (tag === "SCRIPT" || tag === "STYLE" || tag === "NOSCRIPT") return;
      const translated = translateText(node.nodeValue);
      if (translated !== node.nodeValue) {
        node.nodeValue = translated;
      }
    }
    function translateAttributes(element) {
      if (!element || element.nodeType !== Node.ELEMENT_NODE) return;
      for (const name of ATTRIBUTE_NAMES) {
        if (!element.hasAttribute(name)) continue;
        const current = element.getAttribute(name);
        const translated = translateText(current);
        if (translated !== current) {
          element.setAttribute(name, translated);
        }
      }
    }
    function translateSubtree(root) {
      if (!root) return;
      if (root.nodeType === Node.TEXT_NODE) {
        translateTextNode(root);
        return;
      }
      if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_NODE) {
        return;
      }
      const element = root.nodeType === Node.ELEMENT_NODE ? root : document.documentElement;
      if (element instanceof Element) {
        translateAttributes(element);
      }
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
      let current = walker.nextNode();
      while (current) {
        translateTextNode(current);
        current = walker.nextNode();
      }
      if (root instanceof Element || root instanceof Document) {
        const nodes = root.querySelectorAll("*");
        for (const node of nodes) {
          translateAttributes(node);
        }
      }
    }
    function observeDomChanges() {
      const observer = new MutationObserver((mutations) => {
        for (const mutation of mutations) {
          if (mutation.type === "characterData") {
            translateTextNode(mutation.target);
            continue;
          }
          if (mutation.type === "attributes") {
            if (mutation.target instanceof Element) {
              translateAttributes(mutation.target);
            }
            continue;
          }
          if (mutation.type === "childList") {
            for (const node of mutation.addedNodes) {
              translateSubtree(node);
            }
          }
        }
      });
      observer.observe(document.documentElement, {
        subtree: true,
        childList: true,
        characterData: true,
        attributes: true,
        attributeFilter: [
          ...ATTRIBUTE_NAMES
        ]
      });
    }
    function patchAlert() {
      if (!isEnglish || typeof window.alert !== "function") return;
      const nativeAlert = window.alert.bind(window);
      window.alert = (message) => nativeAlert(translateText(String(message ?? "")));
    }
    if (isEnglish) {
      translateSubtree(document.documentElement);
      observeDomChanges();
      patchAlert();
    }
    window.AppI18n = {
      lang,
      isEnglish,
      t,
      translateText,
      apply: translateSubtree
    };
  })();
})();
