// Generated by deno task build from src/shared/js/shell-tabs.ts.
// Do not edit this file directly; edit the TypeScript source instead.
(() => {
  // src/shared/js/shell-tabs.ts
  (() => {
    function isToolId(value) {
      return value === "ascii" || value === "pixel" || value === "resize";
    }
    const tabs = Array.from(document.querySelectorAll("[data-tool-tab]"));
    if (!tabs.length) return;
    const panelByTool = {
      ascii: document.getElementById("panel-ascii"),
      pixel: document.getElementById("panel-pixel"),
      resize: document.getElementById("panel-resize")
    };
    const frameByTool = {
      ascii: document.getElementById("frame-ascii"),
      pixel: document.getElementById("frame-pixel"),
      resize: document.getElementById("frame-resize")
    };
    function ensureFrameLoaded(tool) {
      const frame = frameByTool[tool];
      if (!frame) return;
      if (frame.getAttribute("src")) return;
      const lazySrc = frame.getAttribute("data-src");
      if (lazySrc) {
        frame.setAttribute("src", lazySrc);
      }
    }
    function activate(tool) {
      tabs.forEach((tab) => {
        const isActive = tab.getAttribute("data-tool-tab") === tool;
        tab.classList.toggle("is-active", isActive);
        tab.setAttribute("aria-selected", String(isActive));
        tab.tabIndex = isActive ? 0 : -1;
      });
      Object.entries(panelByTool).forEach(([name, panel]) => {
        if (!panel) return;
        panel.hidden = name !== tool;
        panel.classList.toggle("is-active", name === tool);
      });
      ensureFrameLoaded(tool);
    }
    tabs.forEach((tab) => {
      tab.addEventListener("click", () => {
        const tool = tab.getAttribute("data-tool-tab");
        if (isToolId(tool)) activate(tool);
      });
    });
    activate("ascii");
  })();
})();
